---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dyuv7350/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
