name: Deploy to Live Server

on:
  push:
    branches:
      - live

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🛠️ Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysqli
          tools: composer

      - name: 📦 Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🚀 Sync Files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/tests/**
            **/phpunit.xml*
            **.md
            .env
            env
            writable/logs/*
            writable/session/*
            writable/cache/*
            writable/debugbar/*
